# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='context.proto',
  package='piscan_pb',
  syntax='proto3',
  serialized_pb=_b('\n\rcontext.proto\x12\tpiscan_pb\"\xd0\x01\n\x0eScannerContext\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.piscan_pb.ScannerContext.State\x12\x0c\n\x04\x66req\x18\x02 \x01(\x04\x12\x11\n\tsystemTag\x18\x03 \x01(\t\x12\x10\n\x08\x65ntryTag\x18\x04 \x01(\t\x12\x12\n\nmodulation\x18\x05 \x01(\t\x12\x12\n\nentryIndex\x18\x06 \x01(\t\"3\n\x05State\x12\t\n\x05INVAL\x10\x00\x12\x08\n\x04SCAN\x10\x01\x12\x08\n\x04HOLD\x10\x02\x12\x0b\n\x07RECEIVE\x10\x03\"-\n\x0c\x44\x65modContext\x12\x0f\n\x07squelch\x18\x01 \x01(\x05\x12\x0c\n\x04gain\x18\x02 \x01(\x02\"y\n\x0eGeneralMessage\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.piscan_pb.GeneralMessage.Type\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"(\n\x04Type\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SCANNERCONTEXT_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='piscan_pb.ScannerContext.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCAN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECEIVE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=186,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_SCANNERCONTEXT_STATE)

_GENERALMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='piscan_pb.GeneralMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=367,
  serialized_end=407,
)
_sym_db.RegisterEnumDescriptor(_GENERALMESSAGE_TYPE)


_SCANNERCONTEXT = _descriptor.Descriptor(
  name='ScannerContext',
  full_name='piscan_pb.ScannerContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='piscan_pb.ScannerContext.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freq', full_name='piscan_pb.ScannerContext.freq', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='systemTag', full_name='piscan_pb.ScannerContext.systemTag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryTag', full_name='piscan_pb.ScannerContext.entryTag', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modulation', full_name='piscan_pb.ScannerContext.modulation', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryIndex', full_name='piscan_pb.ScannerContext.entryIndex', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCANNERCONTEXT_STATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=237,
)


_DEMODCONTEXT = _descriptor.Descriptor(
  name='DemodContext',
  full_name='piscan_pb.DemodContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='squelch', full_name='piscan_pb.DemodContext.squelch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain', full_name='piscan_pb.DemodContext.gain', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=284,
)


_GENERALMESSAGE = _descriptor.Descriptor(
  name='GeneralMessage',
  full_name='piscan_pb.GeneralMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='piscan_pb.GeneralMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='piscan_pb.GeneralMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERALMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=407,
)

_SCANNERCONTEXT.fields_by_name['state'].enum_type = _SCANNERCONTEXT_STATE
_SCANNERCONTEXT_STATE.containing_type = _SCANNERCONTEXT
_GENERALMESSAGE.fields_by_name['type'].enum_type = _GENERALMESSAGE_TYPE
_GENERALMESSAGE_TYPE.containing_type = _GENERALMESSAGE
DESCRIPTOR.message_types_by_name['ScannerContext'] = _SCANNERCONTEXT
DESCRIPTOR.message_types_by_name['DemodContext'] = _DEMODCONTEXT
DESCRIPTOR.message_types_by_name['GeneralMessage'] = _GENERALMESSAGE

ScannerContext = _reflection.GeneratedProtocolMessageType('ScannerContext', (_message.Message,), dict(
  DESCRIPTOR = _SCANNERCONTEXT,
  __module__ = 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.ScannerContext)
  ))
_sym_db.RegisterMessage(ScannerContext)

DemodContext = _reflection.GeneratedProtocolMessageType('DemodContext', (_message.Message,), dict(
  DESCRIPTOR = _DEMODCONTEXT,
  __module__ = 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.DemodContext)
  ))
_sym_db.RegisterMessage(DemodContext)

GeneralMessage = _reflection.GeneratedProtocolMessageType('GeneralMessage', (_message.Message,), dict(
  DESCRIPTOR = _GENERALMESSAGE,
  __module__ = 'context_pb2'
  # @@protoc_insertion_point(class_scope:piscan_pb.GeneralMessage)
  ))
_sym_db.RegisterMessage(GeneralMessage)


# @@protoc_insertion_point(module_scope)
